controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#Login Controller
app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout

# Registration Controller
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

# TodoController
app_todo:
    path: /todo
    controller: App\Controller\TodoController::index

create_todo:
    path: /createTodo
    controller: App\Controller\TodoController::createTodo

delete_todo:
    path: /deleteTodo
    controller: App\Controller\TodoController::deleteTodo

update_todo:
    path: /updateTodo
    controller: App\Controller\TodoController::updateTodo

view_edit_todo:
        path: /viewEditTodo
        controller: App\Controller\TodoController::viewEditTodo

# UserController
app_user:
    path: /user/{user}
    controller: App\Controller\UserController::index
